// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwTnCXHSCEeVhnTsgacUk2RLcKpWYVmk',
    appId: '1:254593401446:web:18414dd19594cad9fd23a7',
    messagingSenderId: '254593401446',
    projectId: 'realconnect-8eb18',
    authDomain: 'realconnect-8eb18.firebaseapp.com',
    databaseURL: 'https://realconnect-8eb18-default-rtdb.firebaseio.com',
    storageBucket: 'realconnect-8eb18.appspot.com',
    measurementId: 'G-CEXPFWQR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7PHIEH6-voL10akmE30ri98CrMozergA',
    appId: '1:254593401446:android:ba70be386bf1d2b9fd23a7',
    messagingSenderId: '254593401446',
    projectId: 'realconnect-8eb18',
    databaseURL: 'https://realconnect-8eb18-default-rtdb.firebaseio.com',
    storageBucket: 'realconnect-8eb18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrVOnGvNp85llzYMIP8uaRk_0tY7iqao',
    appId: '1:254593401446:ios:8339bf9bf6bd1262fd23a7',
    messagingSenderId: '254593401446',
    projectId: 'realconnect-8eb18',
    databaseURL: 'https://realconnect-8eb18-default-rtdb.firebaseio.com',
    storageBucket: 'realconnect-8eb18.appspot.com',
    iosClientId: '254593401446-ips9060sudtcrtm3br1ho0a4bo8lm5g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.realConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrVOnGvNp85llzYMIP8uaRk_0tY7iqao',
    appId: '1:254593401446:ios:8339bf9bf6bd1262fd23a7',
    messagingSenderId: '254593401446',
    projectId: 'realconnect-8eb18',
    databaseURL: 'https://realconnect-8eb18-default-rtdb.firebaseio.com',
    storageBucket: 'realconnect-8eb18.appspot.com',
    iosClientId: '254593401446-ips9060sudtcrtm3br1ho0a4bo8lm5g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.realConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPwTnCXHSCEeVhnTsgacUk2RLcKpWYVmk',
    appId: '1:254593401446:web:4dcdb4be551b6ad9fd23a7',
    messagingSenderId: '254593401446',
    projectId: 'realconnect-8eb18',
    authDomain: 'realconnect-8eb18.firebaseapp.com',
    databaseURL: 'https://realconnect-8eb18-default-rtdb.firebaseio.com',
    storageBucket: 'realconnect-8eb18.appspot.com',
    measurementId: 'G-0BSP4T4BX6',
  );

}